import React, { useState } from "react"; import styled from "styled-components"; const PricingPlan = ({ name, price, features }) => { return ( <Column> <Div16> <Div17>{name}</Div17> <Div18> <Div19>${price}</Div19> <Div20>per month</Div20> </Div18> {features.map((feature, index) => ( <Div21 key={index}>{feature}</Div21> ))} <Div25>Select</Div25> </Div16> </Column> );
}; const FAQ = ({ question, answer, isOpen, onToggle }) => { return ( <> <Div47 onClick={onToggle}> <Div48>{question}</Div48> <Div49>{isOpen ? "-" : "+"}</Div49> </Div47> {isOpen && <Div50>{answer}</Div50>} </> );
}; const FooterLink = ({ topic, pages }) => { return ( <Column5> <Div70> <Div71>{topic}</Div71> {pages.map((page, index) => ( <Div72 key={index}>{page}</Div72> ))} </Div70> </Column5> );
}; const Pricing = () => { const pricingPlans = [ { name: "Plan 1 name", price: 5, features: ["Feature", "Feature", "Feature", "Feature"], }, { name: "Plan 2 name", price: 10, features: ["Feature", "Feature", "Feature", "Feature"], }, { name: "Plan 3 name", price: 20, features: ["Feature", "Feature", "Feature", "Feature"], }, ]; const [openFaqIndex, setOpenFaqIndex] = useState(null); const faqs = [ { question: "What's the most frequently asked question?", answer: "Answer the frequently asked question in a simple sentence, a longish paragraph, or even in a list.", }, { question: "How about a second one?", answer: "Answer the second question in a simple sentence, a longish paragraph, or even in a list.", }, { question: "And a third?", answer: "Answer the third question in a simple sentence, a longish paragraph, or even in a list.", }, ]; const footerLinks = [ { topic: "Topic", pages: ["Page", "Page", "Page"], }, { topic: "Topic", pages: ["Page", "Page", "Page"], }, { topic: "Topic", pages: ["Page", "Page", "Page"], }, ]; return ( <Div> <Div2> <Div3>Site name</Div3> <Div4> <Div5>Page</Div5> <Div6>Page</Div6> <Div7>Page</Div7> <Div8>Button</Div8> </Div4> </Div2> <main> <Div9>Pricing page title</Div9> <Div10>And a subheading describing your pricing plans, too</Div10> <Div11> <Div12>Monthly plans</Div12> <Div13>Annual plans</Div13> </Div11> <Div14> <Div15> {pricingPlans.map((plan, index) => ( <PricingPlan key={index} {...plan} /> ))} </Div15> </Div14> <section> <Div46>Heading for FAQs</Div46> {faqs.map((faq, index) => ( <FAQ key={index} {...faq} isOpen={openFaqIndex === index} onToggle={() => setOpenFaqIndex(openFaqIndex === index ? null : index)} /> ))} </section> </main> <Div57> <Div58 /> <Div59> <Div60> <Div61>Site name</Div61> <Div62> <Img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/e1cbc6d58a74886c4d18e6f63acf6123066f74c5a476279d3a0ea678601ba09e?apiKey=a342aafd07af4859aab3668db0c46a94&" /> <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/b1bac3668b19309ab1c82835d154f9962b24bad9c262723d53374e3173c3e762?apiKey=a342aafd07af4859aab3668db0c46a94&" /> <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/c9c8d64becb556072cf4288b2dadd32d18a3ce8e19d5cc15f298f66d1125313b?apiKey=a342aafd07af4859aab3668db0c46a94&" /> <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/0828515f09127d365461d17e1036e88788811bd5c0258116139d171a870fbe56?apiKey=a342aafd07af4859aab3668db0c46a94&" /> </Div62> </Div60> <Div63> <Div64> {footerLinks.map((link, index) => ( <FooterLink key={index} {...link} /> ))} </Div64> </Div63> </Div59> </Div57> </Div> );
}; const Div = styled.div` display: flex; flex-direction: column; align-items: center; padding: 0 20px;
`; const Div2 = styled.div` justify-content: space-between; background-color: #fff; align-self: stretch; display: flex; width: 100%; gap: 20px; font-size: 20px; color: #000; font-weight: 500; line-height: 150%; padding: 56px 80px; @media (max-width: 991px) { max-width: 100%; flex-wrap: wrap; padding: 0 20px; }
`; const Div3 = styled.div` font-family: Inter, sans-serif; margin: auto 0;
`; const Div4 = styled.div` justify-content: space-between; align-items: center; display: flex; gap: 20px; white-space: nowrap; @media (max-width: 991px) { white-space: initial; }
`; const Div5 = styled.div` font-family: Inter, sans-serif; align-self: stretch; margin: auto 0;
`; const Div6 = styled.div` font-family: Inter, sans-serif; align-self: stretch; margin: auto 0;
`; const Div7 = styled.div` font-family: Inter, sans-serif; align-self: stretch; margin: auto 0;
`; const Div8 = styled.div` justify-content: center; border-radius: var(--Spacing-XS, 8px); box-shadow: 0px 1px 2px 0px rgba(0, 0, 0, 0.05); background-color: #000; align-self: stretch; color: #fff; padding: 14px 24px; font: 16px Inter, sans-serif; @media (max-width: 991px) { white-space: initial; padding: 0 20px; }
`; const Div9 = styled.div` color: #000; text-align: center; letter-spacing: -1.28px; margin-top: 80px; font: 700 64px Inter, sans-serif; @media (max-width: 991px) { max-width: 100%; margin-top: 40px; font-size: 40px; }
`; const Div10 = styled.div` color: #828282; text-align: center; margin-top: 24px; font: 400 24px/150% Inter, sans-serif; @media (max-width: 991px) { max-width: 100%; }
`; const Div11 = styled.div` border-radius: 12px; background-color: #f5f5f5; display: flex; margin-top: 24px; gap: 8px; font-size: 16px; color: #000; font-weight: 500; line-height: 150%; padding: 8px;
`; const Div12 = styled.div` font-family: Inter, sans-serif; justify-content: center; border-radius: var(--Spacing-XS, 8px); background-color: #fff; padding: 8px 16px;
`; const Div13 = styled.div` font-family: Inter, sans-serif; justify-content: center; border-radius: var(--Spacing-XS, 8px); background-color: #f5f5f5; padding: 8px 16px;
`; const Div14 = styled.div` align-content: flex-start; flex-wrap: wrap; margin-top: 41px; width: 100%; max-width: 1279px; @media (max-width: 991px) { max-width: 100%; margin-top: 40px; }
`; const Div15 = styled.div` gap: 20px; display: flex; @media (max-width: 991px) { flex-direction: column; align-items: stretch; gap: 0px; }
`; const Column = styled.div` display: flex; flex-direction: column; line-height: normal; width: 33%; margin-left: 0px; @media (max-width: 991px) { width: 100%; }
`; const Div16 = styled.div` justify-content: flex-end; border-radius: 12px; box-shadow: 0px 0px 15px 0px rgba(0, 0, 0, 0.1), 0px 4px 6px -4px rgba(0, 0, 0, 0.1); background-color: #fff; display: flex; width: 100%; flex-grow: 1; flex-direction: column; color: #828282; margin: 0 auto; padding: 48px; @media (max-width: 991px) { margin-top: 32px; padding: 0 20px; }
`; const Div17 = styled.div` color: #000; font: 500 16px/150% Inter, sans-serif;
`; const Div18 = styled.div` display: flex; margin-top: 12px; gap: 8px; color: #000;
`; const Div19 = styled.div` font: 600 40px/110% Inter, sans-serif;
`; const Div20 = styled.div` align-self: start; margin-top: 20px; flex-grow: 1; flex-basis: auto; font: 500 16px/150% Inter, sans-serif;
`; const Div21 = styled.div` margin-top: 32px; font: 500 20px/150% Inter, sans-serif;
`; const Div25 = styled.div` justify-content: center; align-items: center; border-radius: var(--Spacing-XS, 8px); box-shadow: 0px 1px 2px 0px rgba(0, 0, 0, 0.05); background-color: #000; margin-top: 32px; color: #fff; white-space: nowrap; padding: 14px 60px; font: 500 16px/150% Inter, sans-serif; @media (max-width: 991px) { white-space: initial; padding: 0 20px; }
`; const Div46 = styled.div` color: #000; margin-top: 108px; font: 600 40px/110% Inter, sans-serif; @media (max-width: 991px) { max-width: 100%; margin-top: 40px; }
`; const Div47 = styled.div` display: flex; margin-top: 32px; width: 100%; max-width: 1259px; gap: 20px; cursor: pointer; @media (max-width: 991px) { max-width: 100%; flex-wrap: wrap; }
`; const Div48 = styled.div` color: #000; flex-grow: 1; flex-basis: auto; margin: auto 0; font: 400 24px/150% Inter, sans-serif; @media (max-width: 991px) { max-width: 100%; }
`; const Div49 = styled.div` color: #828282; font: 600 40px/110% Inter, sans-serif;
`; const Div50 = styled.div` color: #828282; margin-top: 32px; font: 500 20px/150% Inter, sans-serif; @media (max-width: 991px) { max-width: 100%; }
`; const Div57 = styled.div` background-color: #fff; align-self: stretch; display: flex; margin-top: 120px; width: 100%; flex-direction: column; padding: 0 80px 48px; @media (max-width: 991px) { max-width: 100%; margin-top: 40px; padding: 0 20px; }
`; const Div58 = styled.div` border-color: rgba(230, 230, 230, 1); border-style: solid; border-width: 1px; background-color: #e6e6e6; height: 1px; @media (max-width: 991px) { max-width: 100%; }
`; const Div59 = styled.div` display: flex; margin-top: 47px; width: 100%; gap: 20px; @media (max-width: 991px) { max-width: 100%; flex-wrap: wrap; margin-top: 40px; }
`; const Div60 = styled.div` align-self: start; display: flex; margin-top: 13px; flex-direction: column;
`; const Div61 = styled.div` color: #000; font: 400 24px/150% Inter, sans-serif;
`; const Div62 = styled.div` display: flex; margin-top: 97px; gap: 8px; @media (max-width: 991px) { margin-top: 40px; }
`; const Img = styled.img` aspect-ratio: 1; object-fit: auto; object-position: center; width: 40px;
`; const Div63 = styled.div` flex-grow: 1; flex-basis: auto; @media (max-width: 991px) { max-width: 100%; }
`; const Div64 = styled.div` gap: 20px; display: flex; @media (max-width: 991px) { flex-direction: column; align-items: stretch; gap: 0px; }
`; const Column5 = styled.div` display: flex; flex-direction: column; line-height: normal; width: 33%; margin-left: 20px; @media (max-width: 991px) { width: 100%; }
`; const Div70 = styled.div` justify-content: center; display: flex; flex-grow: 1; flex-direction: column; font-size: 16px; color: #454545; font-weight: 500; white-space: nowrap; line-height: 150%; @media (max-width: 991px) { margin-top: 31px; white-space: initial; }
`; const Div71 = styled.div` color: #000; font-family: Inter, sans-serif;
`; const Div72 = styled.div` font-family: Inter, sans-serif; margin-top: 24px;
`; export default Pricing;